# Generated by Django 5.2.7 on 2025-11-05 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='rooms_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
